version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mymongo
    ports:
      - "27000:27017"
    volumes:
      - mongodata:/data/db
    command: --bind_ip 0.0.0.0

volumes:
  mongodata:
